# Generated by Django 3.0.2 on 2020-09-07 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=1024)),
                ('mail_address', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
